//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPLUSPLUS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductUsed
    {
        public int PU_ID { get; set; }
        public Nullable<System.DateTime> PU_DateBuyed { get; set; }
        public Nullable<int> F_P_ID { get; set; }
        public Nullable<int> F_UserID { get; set; }
        public Nullable<int> PU_ScoreUsed { get; set; }
        public Nullable<bool> PU_IsNewAddress { get; set; }
        public string PU_NewAddress { get; set; }
        public string PU_NewState { get; set; }
        public string PU_NewCity { get; set; }
        public string PU_NewPostalCode { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
