//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPLUSPLUS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductImage
    {
        public int PI_ID { get; set; }
        public byte[] PI_Image { get; set; }
        public Nullable<int> F_P_ID { get; set; }
        public byte[] PI_Thumb { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
