//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPLUSPLUS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.ProductHistories = new HashSet<ProductHistory>();
            this.ProductImages = new HashSet<ProductImage>();
            this.ProductUseds = new HashSet<ProductUsed>();
        }
    
        public int P_ID { get; set; }
        public string P_Brand { get; set; }
        public string P_Description { get; set; }
        public Nullable<int> P_ScoreCost { get; set; }
        public string P_ModelName { get; set; }
        public Nullable<System.DateTime> P_DateAdded { get; set; }
        public Nullable<int> P_Count { get; set; }
        public Nullable<bool> P_Status { get; set; }
        public Nullable<int> F_ProductType_ID { get; set; }
        public Nullable<int> P_Cost { get; set; }
        public string P_Name { get; set; }
    
        public virtual ProductType ProductType { get; set; }
        public virtual ICollection<ProductHistory> ProductHistories { get; set; }
        public virtual ICollection<ProductImage> ProductImages { get; set; }
        public virtual ICollection<ProductUsed> ProductUseds { get; set; }
    }
}
