//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPLUSPLUS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScoreTry
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> LastTryDate { get; set; }
        public Nullable<int> LastTryNumber { get; set; }
        public Nullable<int> TotalTryNumber { get; set; }
        public Nullable<bool> UserStatusForScore { get; set; }
    }
}
