//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPLUSPLUS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop
    {
        public Shop()
        {
            this.ShopImages = new HashSet<ShopImage>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Mobile { get; set; }
        public string ShopName { get; set; }
        public string ShopDescription { get; set; }
        public string ShopTell { get; set; }
        public string ShopState { get; set; }
        public string ShopCity { get; set; }
        public string ShopAddress { get; set; }
        public Nullable<System.DateTime> DateJoined { get; set; }
        public Nullable<int> F_ShopType_ID { get; set; }
        public bool AcceptCode { get; set; }
        public bool AcceptBanner { get; set; }
        public bool AcceptSite { get; set; }
        public bool ShopRegisterStatus { get; set; }
        public string PosterQuotes { get; set; }
        public Nullable<System.DateTime> DateJoinedAccepted { get; set; }
        public string InstagramAddress { get; set; }
        public string PersonalSiteAddress { get; set; }
        public string ShopEmail { get; set; }
        public string ShopFax { get; set; }
    
        public virtual ShopType ShopType { get; set; }
        public virtual ICollection<ShopImage> ShopImages { get; set; }
    }
}
