//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPLUSPLUS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopAdvertisment
    {
        public int Id { get; set; }
        public Nullable<int> ShopId { get; set; }
        public string ShopName { get; set; }
        public string ShopDescription { get; set; }
        public string ShopTell { get; set; }
        public string ShopAddress { get; set; }
        public Nullable<System.DateTime> ShopRequestDate { get; set; }
        public Nullable<System.DateTime> ShopRequestAcceptedDate { get; set; }
        public Nullable<bool> ShopRequestStatus { get; set; }
        public Nullable<bool> ShopAD_FirstClass { get; set; }
        public string ShopAD_Position { get; set; }
        public string ShopState { get; set; }
        public string ShopCity { get; set; }
        public Nullable<int> F_ShopType { get; set; }
    
        public virtual ShopType ShopType { get; set; }
    }
}
