//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPLUSPLUS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopType
    {
        public ShopType()
        {
            this.Shops = new HashSet<Shop>();
            this.ShopAdvertisments = new HashSet<ShopAdvertisment>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string DescriptionOf { get; set; }
        public byte[] ImageOf { get; set; }
    
        public virtual ICollection<Shop> Shops { get; set; }
        public virtual ICollection<ShopAdvertisment> ShopAdvertisments { get; set; }
    }
}
