//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPLUSPLUS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempUserProfile
    {
        public string U_UserName { get; set; }
        public string U_FirstName { get; set; }
        public string U_LastName { get; set; }
        public string U_Gender { get; set; }
        public string U_BirthDate { get; set; }
        public string U_CodeMelli { get; set; }
        public string U_Tell { get; set; }
        public string U_Email { get; set; }
        public string U_Address { get; set; }
        public string U_Degree { get; set; }
        public string U_DegreeField { get; set; }
        public string U_RegisterDate { get; set; }
        public string U_Status { get; set; }
        public string U_Score { get; set; }
        public string U_State { get; set; }
        public string U_City { get; set; }
        public string U_PW { get; set; }
        public string U_SMS_FisrtStstus { get; set; }
        public string U_SMS_SecondStatus { get; set; }
        public string U_RandomCode { get; set; }
        public Nullable<int> Try_Send_Code { get; set; }
        public string U_JobField { get; set; }
        public string U_JobTitle { get; set; }
    }
}
