//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSTools
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMS_Outbox_Operation_Mapping
    {
        public int Id { get; set; }
        public Nullable<int> OutboxId { get; set; }
        public Nullable<int> OperationId { get; set; }
    
        public virtual SMSOutbox SMSOutbox { get; set; }
        public virtual SMSOperation SMSOperation { get; set; }
    }
}
