//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSTools
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSInbox
    {
        public SMSInbox()
        {
            this.SMS_Inbox_Outbox_Mapping = new HashSet<SMS_Inbox_Outbox_Mapping>();
            this.SMS_Inbox_Pattern_Mapping = new HashSet<SMS_Inbox_Pattern_Mapping>();
        }
    
        public int Id { get; set; }
        public string Text { get; set; }
        public string SMS_From { get; set; }
        public Nullable<System.DateTime> RecievedDate { get; set; }
    
        public virtual ICollection<SMS_Inbox_Outbox_Mapping> SMS_Inbox_Outbox_Mapping { get; set; }
        public virtual ICollection<SMS_Inbox_Pattern_Mapping> SMS_Inbox_Pattern_Mapping { get; set; }
    }
}
