//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSTools
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SMSDBEntities : DbContext
    {
        public SMSDBEntities()
            : base("name=SMSDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SMS_Inbox_Outbox_Mapping> SMS_Inbox_Outbox_Mapping { get; set; }
        public virtual DbSet<SMS_Inbox_Pattern_Mapping> SMS_Inbox_Pattern_Mapping { get; set; }
        public virtual DbSet<SMS_Outbox_Operation_Mapping> SMS_Outbox_Operation_Mapping { get; set; }
        public virtual DbSet<SMSInbox> SMSInboxes { get; set; }
        public virtual DbSet<SMSOperation> SMSOperations { get; set; }
        public virtual DbSet<SMSOutbox> SMSOutboxes { get; set; }
        public virtual DbSet<SMSPattern> SMSPatterns { get; set; }
        public virtual DbSet<SMSTemplate> SMSTemplates { get; set; }
    }
}
