//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSTools
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSOperation
    {
        public SMSOperation()
        {
            this.SMS_Outbox_Operation_Mapping = new HashSet<SMS_Outbox_Operation_Mapping>();
            this.SMSTemplates = new HashSet<SMSTemplate>();
        }
    
        public int Id { get; set; }
        public string Operation { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> PatternId { get; set; }
    
        public virtual ICollection<SMS_Outbox_Operation_Mapping> SMS_Outbox_Operation_Mapping { get; set; }
        public virtual SMSPattern SMSPattern { get; set; }
        public virtual ICollection<SMSTemplate> SMSTemplates { get; set; }
    }
}
