//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSTools
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSOutbox
    {
        public SMSOutbox()
        {
            this.SMS_Inbox_Outbox_Mapping = new HashSet<SMS_Inbox_Outbox_Mapping>();
            this.SMS_Outbox_Operation_Mapping = new HashSet<SMS_Outbox_Operation_Mapping>();
        }
    
        public int Id { get; set; }
        public string Text { get; set; }
        public string SMS_To { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public string StatusOne { get; set; }
        public string StatusTwo { get; set; }
    
        public virtual ICollection<SMS_Inbox_Outbox_Mapping> SMS_Inbox_Outbox_Mapping { get; set; }
        public virtual ICollection<SMS_Outbox_Operation_Mapping> SMS_Outbox_Operation_Mapping { get; set; }
    }
}
