//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSTools
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSTemplate
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string DestinationNumber { get; set; }
        public Nullable<int> OperationId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual SMSOperation SMSOperation { get; set; }
    }
}
